version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.15
  build:
    commands:
      - export GO111MODULE=on && go test github.com/Chief-Alchemist/aws-secretsmanager-caching-go/secretcache -v
      - export GO111MODULE=on && go test github.com/Chief-Alchemist/aws-secretsmanager-caching-go/scintegtests -v
